{{- range $clusterName, $cluster := .Values.clusters }}
{{- range $origin := $cluster.origins }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $origin.name }}
  labels:
    app: {{ $origin.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $origin.name }}
  template:
    metadata:
      labels:
        app: {{ $origin.name }}
      annotations:
        k8s.v1.cni.cncf.io/networks:
            '[{ 
                    "name": {{ $origin.multus }},
                    "ips": [{{ $origin.iprange }}],
                    "mac": {{ $origin.mac }},
                    "gateway": [{{ $origin.gateway }}]
            }]'
    spec:
      containers:
        - env:
          - name: NET_GATEWAY
            value: {{ $origin.gateway }}
          - name: REDI_HOST
            value: {{ $cluster.redirector.ip }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: 1094
          name: {{ $origin.name }}
          securityContext:
            privileged: True
          resources:
            {{- toYaml $.Values.originresources | nindent 12 }}
          volumeMounts:
            - mountPath: /rucio
              name: cache-volume
            - mountPath: /etc/grid-security/hostcert.pem
              name: certs
              subPath: hostcert.pem
            - mountPath: /etc/grid-security/hostkey.pem
              name: certs
              subPath: hostcert.key.pem
            - mountPath: /etc/xrootd/macaroon-secret
              name: certs
              subPath: macaroon-secret
      nodeSelector:
        kubernetes.io/hostname: {{ $origin.node }}
      volumes:
        - name: cache-volume
          hostPath:
            path: /mnt/nvme
            type: Directory
        - name: certs
          secret:
            secretName: {{ $origin.certs }}
            items:
              - key: hostcert.pem
                path: hostcert.pem
              - key: hostcert.key.pem
                path: hostcert.key.pem
              - key: macaroon-secret
                path: macaroon-secret
            defaultMode: 0644
---
{{- end }}
{{- end }}