apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
          {{- range $key1, $val1 := .Values.envs}}
            - name: {{ $key1 | upper }}
              value: "{{ $val1  }}"
          {{- end}}
          securityContext:
            privileged: True
          ports:
            - containerPort: 1094
            - containerPort: 1213
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
          volumeMounts:
            - mountPath: /rucio
              name: cache-volume
            - mountPath: /etc/grid-security/hostcert.pem
              name: certs
              subPath: hostcert.pem
            - mountPath: /etc/grid-security/hostkey.pem
              name: certs
              subPath: hostcert.key.pem
            - mountPath: /etc/xrootd/macaroon-secret
              name: certs
              subPath: macaroon-secret
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name:
