---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sense-clean-gen5-01
  name: sense-clean-gen5-01
  namespace: osg-gil
spec:
  selector:
    matchLabels:
      app: sense-clean-gen5-01
  template:
    metadata:
      labels:
        app: sense-clean-gen5-01
    spec:
      tolerations:
      - key: "nautilus.io/sense"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: sense-clean-gen5
        image: "aaarora/sense-cleaner:latest"
        imagePullPolicy: "Always"
        env:
        - name: SENSE_CLEANUP
          value: '1'
        resources:
          limits:
            cpu: 1
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - mountPath: /rucio
          name: sense-clean-gen5-fs
      restartPolicy: Always
      volumes:
      - name: sense-clean-gen5-fs
        persistentVolumeClaim:
          claimName: osg-gen5-nvme  
      nodeSelector: 
        kubernetes.io/hostname: k8s-gen5-01.sdsc.optiputer.net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sense-clean-gen5-02
  name: sense-clean-gen5-02
  namespace: osg-gil
spec:
  selector:
    matchLabels:
      app: sense-clean-gen5-02
  template:
    metadata:
      labels:
        app: sense-clean-gen5-02
    spec:
      tolerations:
      - key: "nautilus.io/sense"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: sense-clean-gen5
        image: "aaarora/sense-cleaner:latest"
        imagePullPolicy: "Always"
        env:
        - name: SENSE_CLEANUP
          value: '1'
        resources:
          limits:
            cpu: 1
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - mountPath: /rucio
          name: sense-clean-gen5-fs
      restartPolicy: Always
      volumes:
      - name: sense-clean-gen5-fs
        persistentVolumeClaim:
          claimName: osg-gen5-nvme 
      nodeSelector: 
        kubernetes.io/hostname: k8s-gen5-02.sdsc.optiputer.net
      
